# Generated by Django 4.1.5 on 2023-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Helthcare', 'Healthcare'), ('Education', 'Education'), ('Others', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='possition',
            field=models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('Project Mannager', 'PM'), ('Software developer', 'SDE'), ('Other', 'Other')], max_length=50),
        ),
    ]
